# Generated by Django 5.2.5 on 2025-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('qr_cord', models.ImageField(blank=True, null=True, upload_to='qecodes/')),
                ('date', models.DateField()),
            ],
        ),
    ]
