# Generated by Django 5.2.5 on 2025-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_cord',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
