# Generated by Django 5.2.5 on 2025-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_alter_event_qr_cord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_cord',
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qecodes/'),
        ),
    ]
