# Generated by Django 5.2.5 on 2025-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_remove_event_qr_cord_event_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
